# Generated by Django 4.1.2 on 2022-10-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bookingdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='age',
        ),
    ]
