# Generated by Django 4.1.2 on 2022-10-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_rents'),
        ('payments', '0003_remove_bookingdetails_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
