# Generated by Django 4.1.2 on 2022-10-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cars', '0002_delete_cars_arc_delete_cars_rents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_Rents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('client_document_identification', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(null=True)),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.CharField(blank=True, max_length=255, null=True)),
                ('total_price_is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('id_cars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carRents', to='cars.car')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationRents', to='cars.location')),
            ],
        ),
    ]
