# Generated by Django 4.1 on 2022-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_location_short_name_alter_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
