# Generated by Django 4.1 on 2022-09-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='location',
            new_name='Flocation',
        ),
    ]
