# Generated by Django 4.1 on 2022-09-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_cars_rents_creator_alter_cars_rents_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars_rents',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='cars_rents',
            name='deposit_currency',
        ),
        migrations.RemoveField(
            model_name='cars_rents',
            name='deposit_is_active',
        ),
        migrations.RemoveField(
            model_name='cars_rents',
            name='total_price_currency',
        ),
    ]
