# Generated by Django 4.1 on 2022-09-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_cars_rents_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars_arc',
            name='type',
        ),
    ]
