# Generated by Django 4.1 on 2022-09-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_cars_arc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars_rents',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='cars_rents',
            name='date_of_entry',
        ),
        migrations.RemoveField(
            model_name='cars_rents',
            name='note',
        ),
    ]
