# Generated by Django 4.1 on 2022-09-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_cars_rents_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars_rents',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
