# Generated by Django 4.1 on 2022-09-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
    ]
